import { ethers } from "hardhat";
import { BigNumber, utils } from "ethers";

async function main() {
  const accounts = await ethers.getSigners();
  const seller = accounts[1];
  const buyer = accounts[2];
  const nftAddress = "0xdfb71a5199aca3a9572ca212ad3720807ecde03c";
  const wethAddress = "0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa";
  const platformAddress = "0x0000000000000000000000000000000000000000";
  const platformFee = 0;
  const priceFeedAddress = "0xe306C1DcCB13e9dB2af5C782ab2e36416C21B43e";

  // //Marketplace Contract Deployment
  // const Buy = await ethers.getContractFactory("MarketPlace");
  // const buy = await Buy.deploy(
  //   nftAddress,
  //   wethAddress,
  //   platformAddress,
  //   platformFee,
  //   priceFeedAddress
  // );
  const buy = await ethers.getContractAt("CheckMarket","0x489B2d24C86b579076Fa266f17D881140cB8F83E");
  console.log(`Buy Contract deployed to: ${buy.address}`);

  //Approving functionality from ERC721 Contract to Marketplace Contract
  const nftMedia = await ethers.getContractAt(
    "ERC721CreatorImplementation",
    nftAddress
  );

  const approveForAllTx = await nftMedia
    .connect(seller)
    .setApprovalForAll(buy.address, true);
  console.log(`Approve transaction submitted to: ${approveForAllTx.hash}`);
  await approveForAllTx.wait(1);

  //Order Parameters
  const fixedPrice = utils.parseEther("0.0000000000000001");
  const uuid = "024a81a0-62ff-444b-8772-a0b32aee2dfc";
  const order = [
    uuid,
    3,
    "0xdfb71a5199aca3a9572ca212ad3720807ecde03c",
    BigNumber.from("1"),
    "0x29F00d7868Adac2AFCc29b3E63Ebd8F269bfCCb6",
    fixedPrice,
    wethAddress,
    ethers.constants.AddressZero,
    0,
    0,
    buyer.address,
  ];

  // const param = order.slice(0, 7);
  // console.log(param);
  // const hashedMessage = ethers.utils.solidityKeccak256(
  //   ["bytes"],
  //   [
  //     ethers.utils.solidityPack(
  //       [
  //         "string",
  //         "uint256",
  //         "address",
  //         "uint256",
  //         "address",
  //         "uint256",
  //         "address",
  //       ],
  //       param
  //     ),
  //   ]
  // );

  // //Seller Signature is generated by signing the hash generated
  const sellerSignature = await seller.signMessage(
    ethers.utils.arrayify("a241bb325e7c5e0a6a078ad23eba907f96cb58303a39859c5d3a18872610a226")
  );
  console.log(sellerSignature);

  // // Approving the WETH to auction house
  const weth = await ethers.getContractAt("WETH", wethAddress);
  const approveTx = await weth.connect(buyer).approve(buy.address, fixedPrice);
  console.log(`Approve transaction submitted to: ${approveTx.hash}`);
  await approveTx.wait();

  //Buying the nft via using signature by Buyer
  const tsn = await buy
    .connect(buyer)
    .buy(order, sellerSignature, { value: fixedPrice });
  console.log(`Buy Creation submitted at: ${tsn.hash}`);
  await tsn.wait();
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
